# Generated by Django 4.0.3 on 2022-06-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_new_slug_alter_service_service_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_img',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='service/'),
        ),
    ]
