# Generated by Django 4.0.3 on 2022-05-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=100)),
                ('service_author', models.CharField(max_length=80)),
                ('service_description', models.TextField()),
            ],
        ),
    ]
