# Generated by Django 4.0.3 on 2022-06-13 10:40

import autoslug.fields
from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='new_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='service_title', unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_author',
            field=tinymce.models.HTMLField(max_length=80),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_title',
            field=tinymce.models.HTMLField(max_length=100),
        ),
    ]
